"""initial schema

Revision ID: cdf91f36b18f
Revises:
Create Date: 2026-08-11 16:15:20.743222+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types referenced by the column definitions below.
import network_defender.database.base
import network_defender.database.types

revision: str = 'cdf91f36b18f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('alert_id', network_defender.database.types.GUID(), nullable=False),
    sa.Column('timestamp', network_defender.database.base.UtcDateTime(), nullable=False),
    sa.Column('last_seen', network_defender.database.base.UtcDateTime(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('rule_triggered', sa.String(length=128), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=True),
    sa.Column('dst_ip', sa.String(length=45), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('packet_summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('tactic', sa.String(length=16), nullable=True),
    sa.Column('technique', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('threat_intel', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('alert_id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_dst_ip'), ['dst_ip'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_alerts_rule_triggered'), ['rule_triggered'], unique=False
        )
        batch_op.create_index(
            'ix_alerts_severity_timestamp', ['severity', 'timestamp'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_alerts_src_ip'), ['src_ip'], unique=False)
        batch_op.create_index('ix_alerts_src_ip_timestamp', ['src_ip', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_index('ix_alerts_status_timestamp', ['status', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_timestamp'), ['timestamp'], unique=False)

    op.create_table('rules',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('window', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('group_by', sa.String(length=32), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('loaded_at', network_defender.database.base.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_rules'))
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_enabled'), ['enabled'], unique=False)

    op.create_table('statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('captured_at', network_defender.database.base.UtcDateTime(), nullable=False),
    sa.Column('total_packets', sa.Integer(), nullable=False),
    sa.Column('total_alerts', sa.Integer(), nullable=False),
    sa.Column('packets_per_second', sa.Float(), nullable=False),
    sa.Column('alerts_by_severity', sa.JSON(), nullable=False),
    sa.Column('top_talkers', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statistics'))
    )
    with op.batch_alter_table('statistics', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_statistics_captured_at'), ['captured_at'], unique=False
        )

    op.create_table('threat_intel_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', network_defender.database.base.UtcDateTime(), nullable=False),
    sa.Column('expires_at', network_defender.database.base.UtcDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threat_intel_cache'))
    )
    with op.batch_alter_table('threat_intel_cache', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_threat_intel_cache_expires_at'), ['expires_at'], unique=False
        )
        batch_op.create_index('uq_threat_intel_cache_provider_ip', ['provider', 'ip'], unique=True)

    op.create_table('packets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', network_defender.database.types.GUID(), nullable=True),
    sa.Column('timestamp', network_defender.database.base.UtcDateTime(), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=True),
    sa.Column('dst_ip', sa.String(length=45), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('raw_summary', sa.Text(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(
        ['alert_id'],
        ['alerts.alert_id'],
        name=op.f('fk_packets_alert_id_alerts'),
        ondelete='CASCADE',
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packets'))
    )
    with op.batch_alter_table('packets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packets_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_packets_src_ip'), ['src_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_packets_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packets_timestamp'))
        batch_op.drop_index(batch_op.f('ix_packets_src_ip'))
        batch_op.drop_index(batch_op.f('ix_packets_alert_id'))

    op.drop_table('packets')
    with op.batch_alter_table('threat_intel_cache', schema=None) as batch_op:
        batch_op.drop_index('uq_threat_intel_cache_provider_ip')
        batch_op.drop_index(batch_op.f('ix_threat_intel_cache_expires_at'))

    op.drop_table('threat_intel_cache')
    with op.batch_alter_table('statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statistics_captured_at'))

    op.drop_table('statistics')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_enabled'))

    op.drop_table('rules')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_timestamp'))
        batch_op.drop_index('ix_alerts_status_timestamp')
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index('ix_alerts_src_ip_timestamp')
        batch_op.drop_index(batch_op.f('ix_alerts_src_ip'))
        batch_op.drop_index('ix_alerts_severity_timestamp')
        batch_op.drop_index(batch_op.f('ix_alerts_rule_triggered'))
        batch_op.drop_index(batch_op.f('ix_alerts_dst_ip'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
