"""
Models for the detection engine.

Data Setup:  Loaded from config and generated by detectors.
Data Input:  Configuration dicts and alert data.
Data Output: Pydantic models.
"""

from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field

from network_defender.constants import MitreTactic, Severity


class DetectionAlert(BaseModel):
    """
    A finding from a heuristic detector, before the alert service enriches it.

    Deliberately smaller than `Alert`: a detector knows what it saw, not what
    it is worth. Deduplication, confidence scoring, MITRE attribution and
    persistence all happen downstream.
    """

    detector_name: str = Field(description="Name of the detector that generated the alert.")
    severity: Severity = Field(description="Severity of the detected activity.")
    tactic: MitreTactic | None = Field(default=None, description="Associated MITRE ATT&CK tactic.")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="Time the alert was generated."
    )
    src_ip: str | None = Field(default=None, description="Source IP associated with the activity.")
    dst_ip: str | None = Field(
        default=None, description="Destination IP associated with the activity."
    )
    description: str = Field(description="Human-readable description of the detected activity.")
    evidence: dict[str, Any] = Field(
        default_factory=dict, description="Raw data or counters supporting the alert."
    )


class DetectorConfig(BaseModel):
    """
    The configuration every detector has, whatever else it adds.

    Subclasses add their own thresholds; the registry validates the matching
    section of config/detectors.json against the subclass, so a bad threshold
    disables one detector rather than failing startup.
    """

    enabled: bool = Field(default=True, description="Whether the detector is enabled.")
