"""
Models for the detection engine.

Data Setup:  Loaded from config and generated by detectors.
Data Input:  Configuration dicts and alert data.
Data Output: Pydantic models.
"""

from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field

from network_defender.constants import MitreTactic, Severity


class DetectionAlert(BaseModel):
    """
    An alert generated by a heuristic detector.
    """
    detector_name: str = Field(description="Name of the detector that generated the alert.")
    severity: Severity = Field(description="Severity of the detected activity.")
    tactic: MitreTactic | None = Field(default=None, description="Associated MITRE ATT&CK tactic.")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Time the alert was generated."
    )
    src_ip: str | None = Field(default=None, description="Source IP associated with the activity.")
    dst_ip: str | None = Field(default=None, description="Destination IP associated with the activity.")
    description: str = Field(description="Human-readable description of the detected activity.")
    evidence: dict[str, Any] = Field(default_factory=dict, description="Raw data or counters supporting the alert.")


class DetectorConfig(BaseModel):
    """
    Base configuration for a detector.
    """
    enabled: bool = Field(default=True, description="Whether the detector is enabled.")
